### ISSUE TITLE
How install?

### ISSUE THREAD

**Issue by ctuxboy** [jflepp/PicoMailForms#1]
Hello,
I will trying your plugin, but can't figured out how install.
1. Download the zip from Github
2. Uploas the unzipped folder 'PicoMailForms-master' and rename it 'PicoMailForms'
3. Add this code in a test.md file:
```
[form]
  [text mail]E-Mail[/text]
  [text]some other information[/text]
[/form]
```

4. Adding this code in the config/config.yml (okay i would chanfg this, but i leave it for testing):
```
Mail:
    SenderName: test.ch
    Host: server.test.ch
    UserName: test@test.ch
    Password: test
    Port: 587
    OperatorMail: testuser@test.ch
```

After that my test-website shows a blank page with an 500 error.

I used Picocms a week now, but for me as beginner it is not so easy installing without a good step-by-step guide and i'm not familiar with composer at the moment.

Hope you can adding more detailed steps how can implement your plugin in picocms? Where adding the config and content snippets?

**Comment by fl3pp** [comment]
Hello ctuxboy, 

You have to install the plugin using composer. A "legacy" installation using the files only is not supported as composer takes care for PicoMailForms dependencies and namespaces. 

According to the pico docs, pico also recommends installing pico using composer: 

>Starting with Pico 2.0 we recommend installing Pico using Composer whenever possible

[Pico Doc](http://picocms.org/docs/) > Install > I want to install pico using composer

After you correctly installed pico using composer, you can install PicoMailForms using followig command: 

```
composer require jflepp/picomailformsplugin
```
FYI: composer is a kind of a nuget or npm for php and does it's job quite good. It also takes care for auto loading in PHP (which PHP can't do properly by default). [composer](https://getcomposer.org)

Please let me know if that worked for you

**Comment by ctuxboy** [comment]
Hi @jflepp,
Thx for the help.
Yesterday evening i try install Pico for the first time with composer.
I have a few question about composer, asked on the picocms github Page.
But it works well and happy i have SSH access to my hosting.
The problem is, some of my clients has no SSH access to they hosting. So i can't use your plugin on they're hosting?

Sorry about my poor english.

**Comment by fl3pp** [comment]
Hello @ctuxboy, 
You could install your page locally and then push the source files (including `./vendor` and the plugin directory) via ftp/share/etc to the server. 
The problem is that the plugin is being configured in the `./vendor` directory during the installation, so you need to you install it using composer. But there is no need to install it on the server directly (although i would recommend it)

**Comment by ctuxboy** [comment]
Oh okay,
I understand:
1. Installing Picocms and our plugin locally
2. Upload the Pico installation to server's webroot.

**Comment by fl3pp** [comment]
exactly
please let me know if that works for you

**Comment by ctuxboy** [comment]
@jflepp 
I try it and it works well!
No server erro anymore.

Adding a mailform on a webpage.

Adding the settings in config/config.yml

```
Mail:
    SenderName: Christophe
    Host: smtp.gmail.com
    UserName: ***@gmail.com
    Password: ***
    Port: 587
    OperatorMail: christophe@my_domain.be
```

Trying send a mail, but gives an error:
_An error occured while sending your message. Please contact the site administrator._

What i see, in the [gmail smtp settings](https://www.lifewire.com/what-are-the-gmail-smtp-settings-1170854), there is an extra option:
**Gmail SMTP TLS/SSL required: yes**

Is it possible adding this?

**Comment by fl3pp** [comment]
SLL SMPT is enabled by default and there is no option to disable it

**Comment by fl3pp** [comment]
I think your issue is now resolved as the installation workes using composer
best regards

**Comment by ctuxboy** [comment]
It works installing with composer, but sending emails, doesn't work at this moment.
Try it again in the next daus ;-)
If it not works i can open another issue.

**Comment by ctuxboy** [comment]
Installing with composer works, but sending emails doesn't work.
Try it again in the next days.
